import type { DashboardSnapshot, MetricSummary } from "./types";

export const emptyMetrics: MetricSummary = {
  workerRequests: 0,
  workerErrors: 0,
  d1Queries: 0,
  r2Operations: 0,
  r2StorageBytes: 0,
  kvOperations: 0,
  kvStorageBytes: 0,
  zoneRequests: 0,
  zoneSecurityEvents: 0,
  auditEvents: 0,
  auditFailures: 0,
  logpushJobs: 0,
  logpushEnabledJobs: 0,
  workerLogEvents: 0,
  workerTraceEvents: 0,
  workerObservabilityFields: 0,
  workerObservabilityDestinations: 0,
  collectorApiCalls: 0,
  collectorApiErrors: 0,
};

export const emptySnapshot: DashboardSnapshot = {
  generatedAt: "",
  range: "24h",
  live: false,
  cached: false,
  inventory: { workers: 0, pages: 0, d1: 0, r2: 0, kv: 0, zones: 0 },
  metrics: emptyMetrics,
  resources: [],
  usagePanels: [],
  health: [
    {
      id: "connection",
      service: "Connection",
      status: "unknown",
      label: "Setup required",
      detail: "Connect a Cloudflare API token to load live inventory and usage.",
    },
  ],
  issues: [],
  zones: {
    zones: 0,
    activeZones: 0,
    requests: 0,
    securityEvents: 0,
    topHosts: [],
  },
  audit: {
    events: 0,
    failures: 0,
    apiEvents: 0,
    dashboardEvents: 0,
    recent: [],
  },
  logpush: {
    jobs: 0,
    enabledJobs: 0,
    workersTraceJobs: 0,
    auditJobs: 0,
    disabledJobs: 0,
    recent: [],
  },
  observability: {
    logEvents: 0,
    errorEvents: 0,
    traces: 0,
    fields: 0,
    destinations: 0,
    configuredWorkers: 0,
    fullSampleWorkers: 0,
    liveTailAvailable: false,
    recentEvents: [],
    gaps: [],
  },
  collector: {
    apiCalls: 0,
    apiErrors: 0,
    endpoints: [],
  },
};
